#!/bin/bash

decomposePar
mpirun -np 16 --use-hwthread-cpus renumberMesh -overwrite -parallel
mpirun -np 16 --use-hwthread-cpus potentialFoam -parallel -initialiseUBCs
mpirun -np 16 --use-hwthread-cpus pimpleFoam -parallel > logRun &
