#!/bin/bash

decomposePar
mpirun -np 22 --use-hwthread-cpus renumberMesh -overwrite -parallel
mpirun -np 22 --use-hwthread-cpus potentialFoam -parallel -initialiseUBCs
mpirun -np 22 --use-hwthread-cpus pimpleFoam -parallel > logRun &
