#!/bin/bash

decomposePar
mpirun -np 22 -bind-to core -bind-to socket renumberMesh -overwrite -parallel
mpirun -np 22 -bind-to core -bind-to socket potentialFoam -parallel -initialiseUBCs
mpirun -np 22 -bind-to core -bind-to socket pimpleFoam -parallel > logRun &
