#!/bin/bash

sh allClean

blockMesh
surfaceFeatureExtract
decomposePar
mpirun -np 16 --use-hwthread-cpus snappyHexMesh -overwrite -parallel > logMesh
mpirun -np 16 --use-hwthread-cpus checkMesh -parallel -allTopology -allGeometry -writeSets vtk > logCheckMesh

reconstructParMesh -constant

rm -rf ./processor* ./postProcessing ./0
cp -r 0.org/. 0
